# Generated by Django 2.1.7 on 2019-03-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('laocation', models.CharField(max_length=200)),
                ('date_time_connection', models.DateTimeField(verbose_name='date time of the request')),
            ],
        ),
    ]
